import java.util.*;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class SHA512hash
{
	public static String encryptThisString(String input)
	{
		try
		{
			// getInstance() methos is called with SHA-512 algo
			MessageDigest md=MessageDigest.getInstance("SHA-512");
			

			//digest() method is called
			//to calculate message digest of input string
			//returned as attay of byte

			byte[] messageDigest =md.digest(input.getBytes());

			//convert byte array into signum type :

			BigInteger no=new BigInteger(1,messageDigest);

			//convert message digest into hex value

			String hashtext=no.toString(16);

			//Add preceding 0s to make it 32bit
			
			while(hashtext.length() < 32)
			{
				hashtext="0"+hashtext;
			}	

			//return the hashtext
			return hashtext;
		}
		catch(NoSuchAlgorithmException e)
		{
			throw new RuntimeException(e);
		}
	}

	public static void main(String[] args) throws NoSuchAlgorithmException
	{
		System.out.println("HashCode Generated by SHA-512 for :");

		Scanner sc=new Scanner(System.in);
		System.out.print("Enter String : ");
		String s1=sc.next();

		System.out.println(s1+" : "+encryptThisString(s1));
	}
}